name: flow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.42
  openai_realtime_dart: ^0.0.3
  path_provider: ^2.1.5
  provider: ^6.1.2
  record: ^5.2.0
  xml: ^6.5.0
  flutter_riverpod: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fpdart: ^1.1.1
  figma_squircle: ^0.5.3
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
